/** Verified Unsplash photo URLs (checked live; avoid IDs that 404 over time). */
function unsplash(photoId: string, width = 900): string {
  return `https://images.unsplash.com/${photoId}?auto=format&fit=crop&w=${width}&q=80`;
}

const PRODUCT_PHOTOS: Record<string, string[]> = {
  Laptops: [
    unsplash("photo-1496181133206-80ce9b88a853"),
    unsplash("photo-1517336714731-489689fd1ca8"),
    unsplash("photo-1593642632823-8f785ba67e45"),
    unsplash("photo-1484788984921-03950022c9ef"),
    unsplash("photo-1525547719571-a2d4ac8945e2"),
    unsplash("photo-1588872657578-7efd1f1555ed"),
    unsplash("photo-1541807084-5c52b6b3adef"),
    unsplash("photo-1498050108023-c5249f4df085"),
  ],
  Smartphones: [
    unsplash("photo-1511707171634-5f897ff02aa9"),
    unsplash("photo-1592899677977-9c10ca588bbd"),
    unsplash("photo-1510557880182-3d4d3cba35a5"),
    unsplash("photo-1580910051074-3eb694886505"),
    unsplash("photo-1601784551446-20c9e07cdbdb"),
    unsplash("photo-1598327105666-5b89351aff97"),
    unsplash("photo-1565849904461-04a58ad377e0"),
    unsplash("photo-1585060544812-6b45742d762f"),
  ],
  Audio: [
    unsplash("photo-1505740420928-5e560c06d30e"),
    unsplash("photo-1572569511254-d8f925fe2cbb"),
    unsplash("photo-1484704849700-f032a568e944"),
    unsplash("photo-1608043152269-423dbba4e7e1"),
    unsplash("photo-1545454675-3531b543be5d"),
    unsplash("photo-1546435770-a3e426bf472b"),
    unsplash("photo-1487215078519-e21cc028cb29"),
    unsplash("photo-1618366712010-f4ae9c647dcb"),
  ],
  Accessories: [
    unsplash("photo-1587829741301-dc798b83add3"),
    unsplash("photo-1527864550417-7fd91fc51a46"),
    unsplash("photo-1625948515291-69613efd103f"),
    unsplash("photo-1625723044792-44de16ccb4e9"),
    unsplash("photo-1593640408182-31c70c8268f5"),
    unsplash("photo-1609081219090-a6d81d3085bf"),
    unsplash("photo-1545127398-14699f92334b"),
    unsplash("photo-1527814050087-3793815479db"),
  ],
};

const CATEGORY_PHOTOS: Record<string, string> = {
  Laptops: unsplash("photo-1496181133206-80ce9b88a853", 800),
  Smartphones: unsplash("photo-1511707171634-5f897ff02aa9", 800),
  Audio: unsplash("photo-1505740420928-5e560c06d30e", 800),
  Accessories: unsplash("photo-1491933382434-500287f9b54b", 800),
};

/** Hero storefront photo (laptop workspace). */
export const HERO_IMAGE = unsplash("photo-1517336714731-489689fd1ca8", 1200);

/** Category showcase image. */
export function categoryCatalogImage(categoryName: string): string {
  return CATEGORY_PHOTOS[categoryName] ?? PRODUCT_PHOTOS.Laptops[0];
}

/** Product card image — unique photo per category index. */
export function productCatalogImage(categoryName: string, index: number): string {
  const pool = PRODUCT_PHOTOS[categoryName] ?? PRODUCT_PHOTOS.Laptops;
  return pool[index % pool.length];
}


export type SeedCategory = {
  name: string;
  description: string;
};

export type SeedProduct = {
  name: string;
  description: string;
  price: number;
  brand: string;
  category: string;
  featured?: boolean;
  stock: number;
  rating?: number;
  reviewCount?: number;
  attributes?: Record<string, unknown>;
};

export const seedCategories: SeedCategory[] = [
  {
    name: "Laptops",
    description: "Performance laptops for work, study, and development.",
  },
  {
    name: "Smartphones",
    description: "Flagship and mid-range phones with modern cameras.",
  },
  {
    name: "Audio",
    description: "Headphones, earbuds, speakers, and studio gear.",
  },
  {
    name: "Accessories",
    description: "Keyboards, docks, stands, and everyday essentials.",
  },
];

export const seedProducts: SeedProduct[] = [
  {
    name: "NovaBook Pro 14",
    description:
      "14-inch developer laptop with 16GB RAM, 512GB SSD, and all-day battery for frontend and backend workflows.",
    price: 78999,
    brand: "Nova",
    category: "Laptops",
    featured: true,
    stock: 24,
    rating: 4.7,
    reviewCount: 128,
    attributes: { ram: 16, storage: 512, display: "14-inch", batteryHours: 12 },
  },
  {
    name: "AeroLite 15",
    description: "Lightweight laptop with balanced performance for students and remote professionals.",
    price: 64999,
    brand: "Aero",
    category: "Laptops",
    featured: true,
    stock: 18,
    rating: 4.5,
    reviewCount: 86,
    attributes: { ram: 16, storage: 256, display: "15.6-inch", batteryHours: 10 },
  },
  {
    name: "DevStation X16",
    description: "Workstation laptop with dedicated graphics for Docker, VMs, and creative workloads.",
    price: 119999,
    brand: "DevStation",
    category: "Laptops",
    featured: true,
    stock: 9,
    rating: 4.8,
    reviewCount: 54,
    attributes: { ram: 32, storage: 1024, display: "16-inch", batteryHours: 9 },
  },
  {
    name: "NovaBook Air 13",
    description: "Ultra-portable laptop focused on battery life and quiet everyday computing.",
    price: 72999,
    brand: "Nova",
    category: "Laptops",
    stock: 15,
    rating: 4.4,
    reviewCount: 41,
    attributes: { ram: 16, storage: 512, display: "13-inch", batteryHours: 14 },
  },
  {
    name: "CarbonBook 17",
    description: "Large-screen performance laptop with high refresh display for design and gaming.",
    price: 98999,
    brand: "Carbon",
    category: "Laptops",
    stock: 11,
    rating: 4.6,
    reviewCount: 67,
    attributes: { ram: 32, storage: 1024, display: "17.3-inch", batteryHours: 8 },
  },
  {
    name: "CloudLite 14",
    description: "Budget-friendly cloud-first laptop optimized for browser-based workflows and video calls.",
    price: 45999,
    brand: "CloudLite",
    category: "Laptops",
    stock: 34,
    rating: 4.2,
    reviewCount: 112,
    attributes: { ram: 8, storage: 256, display: "14-inch", batteryHours: 11 },
  },
  {
    name: "StudioPad Pro",
    description: "2-in-1 convertible with stylus support for sketching, notes, and hybrid work.",
    price: 84999,
    brand: "StudioPad",
    category: "Laptops",
    featured: true,
    stock: 14,
    rating: 4.5,
    reviewCount: 39,
    attributes: { ram: 16, storage: 512, display: "13.5-inch touch", batteryHours: 10 },
  },
  {
    name: "TitanWork 15",
    description: "Thermal-optimized laptop for long compile sessions, data analysis, and backend development.",
    price: 109999,
    brand: "Titan",
    category: "Laptops",
    stock: 8,
    rating: 4.7,
    reviewCount: 29,
    attributes: { ram: 32, storage: 2048, display: "15.6-inch", batteryHours: 9 },
  },
  {
    name: "PulsePhone 12",
    description: "Premium smartphone with bright OLED display, fast charging, and excellent low-light camera.",
    price: 54999,
    brand: "Pulse",
    category: "Smartphones",
    featured: true,
    stock: 40,
    rating: 4.6,
    reviewCount: 210,
    attributes: { storage: 256, cameraMp: 50, batteryMah: 4800 },
  },
  {
    name: "PulsePhone SE",
    description: "Affordable daily driver with smooth performance and reliable battery life.",
    price: 24999,
    brand: "Pulse",
    category: "Smartphones",
    stock: 55,
    rating: 4.3,
    reviewCount: 142,
    attributes: { storage: 128, cameraMp: 48, batteryMah: 5000 },
  },
  {
    name: "FramePhone Max",
    description: "Large-screen smartphone with pro video tools and all-day endurance.",
    price: 69999,
    brand: "Frame",
    category: "Smartphones",
    featured: true,
    stock: 22,
    rating: 4.5,
    reviewCount: 88,
    attributes: { storage: 512, cameraMp: 64, batteryMah: 5200 },
  },
  {
    name: "FramePhone Ultra",
    description: "Flagship camera phone with telephoto lens and cinematic stabilization.",
    price: 89999,
    brand: "Frame",
    category: "Smartphones",
    stock: 16,
    rating: 4.8,
    reviewCount: 74,
    attributes: { storage: 512, cameraMp: 72, batteryMah: 5000 },
  },
  {
    name: "Orbit X5",
    description: "Compact 5G phone with premium build and one-handed ergonomics.",
    price: 42999,
    brand: "Orbit",
    category: "Smartphones",
    stock: 31,
    rating: 4.4,
    reviewCount: 96,
    attributes: { storage: 256, cameraMp: 50, batteryMah: 4500 },
  },
  {
    name: "ZenMobile Neo",
    description: "Clean software experience with long update support and efficient chipset.",
    price: 31999,
    brand: "ZenMobile",
    category: "Smartphones",
    stock: 48,
    rating: 4.3,
    reviewCount: 121,
    attributes: { storage: 128, cameraMp: 48, batteryMah: 5100 },
  },
  {
    name: "Spark 5G Plus",
    description: "Mid-range 5G phone with smooth 120Hz display and fast wired charging.",
    price: 37999,
    brand: "Spark",
    category: "Smartphones",
    stock: 37,
    rating: 4.4,
    reviewCount: 83,
    attributes: { storage: 256, cameraMp: 50, batteryMah: 4700 },
  },
  {
    name: "PulsePhone Mini",
    description: "Small-form-factor phone for minimalists who still want flagship cameras.",
    price: 49999,
    brand: "Pulse",
    category: "Smartphones",
    stock: 19,
    rating: 4.5,
    reviewCount: 52,
    attributes: { storage: 256, cameraMp: 48, batteryMah: 4200 },
  },
  {
    name: "SoundWave ANC Headphones",
    description: "Over-ear noise cancelling headphones with 30-hour battery and studio-grade clarity.",
    price: 12999,
    brand: "SoundWave",
    category: "Audio",
    featured: true,
    stock: 30,
    rating: 4.7,
    reviewCount: 311,
    attributes: { wireless: true, anc: true, batteryHours: 30 },
  },
  {
    name: "SoundWave Buds Pro",
    description: "Compact earbuds with adaptive ANC and low-latency mode for calls and media.",
    price: 7999,
    brand: "SoundWave",
    category: "Audio",
    stock: 64,
    rating: 4.4,
    reviewCount: 189,
    attributes: { wireless: true, anc: true, batteryHours: 8 },
  },
  {
    name: "SoundWave Studio",
    description: "Closed-back studio headphones tuned for mixing, editing, and long listening sessions.",
    price: 15999,
    brand: "SoundWave",
    category: "Audio",
    featured: true,
    stock: 21,
    rating: 4.6,
    reviewCount: 98,
    attributes: { wireless: false, anc: false, driverMm: 50 },
  },
  {
    name: "BassBox Portable Speaker",
    description: "Water-resistant Bluetooth speaker with deep bass and 18-hour playback.",
    price: 5999,
    brand: "BassBox",
    category: "Audio",
    stock: 42,
    rating: 4.3,
    reviewCount: 144,
    attributes: { wireless: true, waterproof: "IPX7", batteryHours: 18 },
  },
  {
    name: "ClipMic Wireless",
    description: "Dual wireless lavalier kit for creators, interviews, and product demos.",
    price: 9999,
    brand: "ClipMic",
    category: "Audio",
    stock: 26,
    rating: 4.5,
    reviewCount: 61,
    attributes: { wireless: true, rangeMeters: 200, batteryHours: 7 },
  },
  {
    name: "EchoDesk Speakers",
    description: "Desktop speaker pair with balanced tuning for music, calls, and daily desk work.",
    price: 11499,
    brand: "EchoDesk",
    category: "Audio",
    stock: 18,
    rating: 4.4,
    reviewCount: 47,
    attributes: { wireless: true, stereo: true, powerWatts: 40 },
  },
  {
    name: "Vinyl Air Max",
    description: "Premium open-ear headphones with airy soundstage and lightweight frame.",
    price: 18999,
    brand: "Vinyl",
    category: "Audio",
    stock: 12,
    rating: 4.7,
    reviewCount: 33,
    attributes: { wireless: true, anc: false, batteryHours: 22 },
  },
  {
    name: "StageMon In-Ear",
    description: "Stage-ready in-ear monitors with replaceable cables and secure fit.",
    price: 6999,
    brand: "StageMon",
    category: "Audio",
    stock: 29,
    rating: 4.2,
    reviewCount: 58,
    attributes: { wireless: false, driverType: "balanced armature" },
  },
  {
    name: "KeyFlow Mechanical Keyboard",
    description: "Hot-swappable mechanical keyboard with RGB and compact layout for developers.",
    price: 6999,
    brand: "KeyFlow",
    category: "Accessories",
    stock: 45,
    rating: 4.5,
    reviewCount: 97,
    attributes: { switches: "linear", layout: "75%", wireless: true },
  },
  {
    name: "GlideTrack Precision Mouse",
    description: "Ergonomic wireless mouse with multi-device pairing and long battery life.",
    price: 3999,
    brand: "GlideTrack",
    category: "Accessories",
    stock: 72,
    rating: 4.2,
    reviewCount: 63,
    attributes: { dpi: 3200, wireless: true },
  },
  {
    name: "DockPro USB-C Hub",
    description: "11-in-1 USB-C dock with dual display support, ethernet, and fast SD transfer.",
    price: 8999,
    brand: "DockPro",
    category: "Accessories",
    featured: true,
    stock: 28,
    rating: 4.6,
    reviewCount: 74,
    attributes: { ports: 11, displaySupport: "dual 4K" },
  },
  {
    name: "ErgoStand Laptop Stand",
    description: "Adjustable aluminum stand that improves posture and airflow for laptops up to 17 inches.",
    price: 3499,
    brand: "ErgoStand",
    category: "Accessories",
    stock: 58,
    rating: 4.4,
    reviewCount: 102,
    attributes: { material: "aluminum", maxDisplayInches: 17 },
  },
  {
    name: "ThunderLink Cable Kit",
    description: "Braided USB-C and Thunderbolt cable set for charging, data, and display output.",
    price: 2999,
    brand: "ThunderLink",
    category: "Accessories",
    stock: 90,
    rating: 4.3,
    reviewCount: 88,
    attributes: { cables: 3, maxWatts: 100 },
  },
  {
    name: "WebCam Pro 4K",
    description: "4K webcam with autofocus, dual mics, and privacy shutter for remote work.",
    price: 8499,
    brand: "WebCam",
    category: "Accessories",
    featured: true,
    stock: 33,
    rating: 4.5,
    reviewCount: 71,
    attributes: { resolution: "4K", fps: 30, hdr: true },
  },
  {
    name: "PadFlow XL Mousepad",
    description: "Extended desk mat with stitched edges and smooth glide for gaming and work.",
    price: 1999,
    brand: "PadFlow",
    category: "Accessories",
    stock: 120,
    rating: 4.1,
    reviewCount: 156,
    attributes: { size: "900x400mm", surface: "speed" },
  },
  {
    name: "ChargeStack GaN 100W",
    description: "Compact GaN charger with dual USB-C and USB-A ports for travel and desk setups.",
    price: 4499,
    brand: "ChargeStack",
    category: "Accessories",
    stock: 66,
    rating: 4.6,
    reviewCount: 92,
    attributes: { maxWatts: 100, ports: 3, gan: true },
  },
];
