// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

function envUrl(name: string): string | undefined {
  const value = process.env[name];
  if (typeof value !== "string" || value.trim() === "") return undefined;
  return value;
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: envUrl("DATABASE_URL"),
    shadowDatabaseUrl: envUrl("SHADOW_DATABASE_URL"),
  },
});
